name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: '11'
      ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk
      # Clear env vars that can inject JVM options and cause the "main class '-Xmx64m'" error
      _JAVA_OPTIONS: ''
      JAVA_TOOL_OPTIONS: ''
      GRADLE_OPTS: ''
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Android SDK command-line tools
        run: |
          mkdir -p "${ANDROID_SDK_ROOT}/cmdline-tools"
          cd "${ANDROID_SDK_ROOT}/cmdline-tools"
          curl -fsSL "https://dl.google.com/android/repository/commandlinetools-linux-10925496_latest.zip" -o cmdline.zip
          unzip -q cmdline.zip
          rm cmdline.zip
          mv cmdline-tools latest
        shell: bash

      - name: Update PATH and install required SDK packages
        run: |
          export PATH="${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin:${ANDROID_SDK_ROOT}/platform-tools:${PATH}"
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"
        shell: bash

      - name: Debug Java and env
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          java -version || true
          ./gradlew -v || true
          echo "_JAVA_OPTIONS='${_JAVA_OPTIONS}'"
          echo "JAVA_TOOL_OPTIONS='${JAVA_TOOL_OPTIONS}'"
          echo "GRADLE_OPTS='${GRADLE_OPTS}'"
        shell: bash

      - name: Build APK (debug)
        run: |
          # ensure problematic env vars are not affecting gradle at runtime
          unset _JAVA_OPTIONS || true
          unset JAVA_TOOL_OPTIONS || true
          unset GRADLE_OPTS || true
          ./gradlew clean assembleDebug --no-daemon
        shell: bash

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: app/build/outputs/**/*.apk
